### PR TITLE
OIGTLIO Hardware Module adding video

### PR DESCRIPTION
**Pull request by errollgarner**
Adds video support to IGTLIO Hardware Module

### CODE REVIEW

File: IbisHardwareIGSIO/ibishardwareIGSIO.cpp [hunk 1]
```diff
@@ -484,28 +513,38 @@ int IbisHardwareIGSIO::FindToolByName( QString name )
...
+    if( tool->sceneObject->IsA( "CameraObject" ) )
+    {
+        vtkSmartPointer<CameraObject> cam = CameraObject::SafeDownCast( tool->sceneObject );
+        if(tool->flipYAxis){
+            cam->SetVideoInputData( tool->flipYFilter->GetOutput() );
+        }else{
+            cam->SetVideoInputData( imageContent );
+        }
+    }
+    else if( tool->sceneObject->IsA( "UsProbeObject" ) )
```
Comment (drouin-simon) [inline IbisHardwareIGSIO/ibishardwareIGSIO.cpp:543]: UsProbe can't have its y flipped?

File: IbisHardwareIGSIO/configio.cpp [hunk 2]
```diff
@@ -19,6 +19,10 @@ void ServerConfig::Serialize( Serializer * ser )
 {
     ::Serialize( ser, "ServerName", m_serverName );
     ::Serialize( ser, "IPAddress", m_ipAddress );
+    ::Serialize( ser, "Type", m_type );
+    ::Serialize( ser, "Protocol", m_protocol );
+    ::Serialize( ser, "DeviceName", m_deviceName );
+    ::Serialize( ser, "DeviceType", m_deviceType );
```
Comment (drouin-simon) [inline IbisHardwareIGSIO/configio.cpp:25]: Why do we need devicename and devicetype. This is getting confusion. Too many things called device.

File: IbisHardwareIGSIO/configio.cpp [hunk 3]
```diff
@@ -29,8 +33,9 @@ void ToolConfig::Serialize( Serializer * ser )
 {
     ::Serialize( ser, "ToolName", ToolName );
     ::Serialize( ser, "ToolType", ToolType );
-    ::Serialize( ser, "ToolModelFile", ToolModelFile);
-    ::Serialize(ser, "ToolParamFile", ToolParamFile);
+    ::Serialize( ser, "ToolModelFile", ToolModelFile );
+    ::Serialize( ser, "ToolParamFile", ToolParamFile );
+    ::Serialize( ser, "FlipYAxis", FlipYAxis );
```
Comment (drouin-simon) [inline IbisHardwareIGSIO/configio.cpp:38]: Why does  the hardware module need to know that. Shouldn't we flip the image inside OpenIGTLinkIO and simplify life for the programmer?

File: IbisHardwareIGSIO/ibishardwareIGSIO.cpp (hunk 1 above)
Comment (errollgarner) [reply IbisHardwareIGSIO/ibishardwareIGSIO.cpp:543]: It definitely can. I'll add to the probe as well.

File: IbisHardwareIGSIO/configio.cpp (hunk 2 above)
Comment (errollgarner) [reply IbisHardwareIGSIO/configio.cpp:25]: I used the same labels as in OpenIGTLink, but yes it might be confusing to use DeviceName for two different things. In fact DeviceName isn't necessary. We could decide to use the ServerName as DeviceName internally for OpenIGTLink. I didn't want to add restrictions, but it wouldn't be strictly necessary to have both. I can remove it. DeviceType is necessary though. It specifies in OpenIGTLink what kind of messages are being received (e.g. IMAGE, VIDEO). We could again name it differently if we think it's confusing. I just used the same name as was used internally in OIGTL.

File: IbisHardwareIGSIO/configio.cpp (hunk 3 above)
Comment (errollgarner) [reply IbisHardwareIGSIO/configio.cpp:38]: I thought it was easiest to do it on the client side and specify it in the config file, but it could surely be done differently. You mean you would add the flipping to the OpenIGTLinkIO connector? And pass the parameter to it in the constructor?

**Comment by nist-anka** [comment]
I tried to build on Ubuntu 18.04 and got:
[ 52%] Building CXX object IbisHardwareIGSIO/CMakeFiles/IbisHardwareIGSIO.dir/ibishardwareIGSIO.cpp.o
/home/anka/ibis_work_sysQt/ibis/IbisHardwareIGSIO/ibishardwareIGSIO.cpp: In member function ‘void IbisHardwareIGSIO::Connect(std::__cxx11::string, int, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)’:
/home/anka/ibis_work_sysQt/ibis/IbisHardwareIGSIO/ibishardwareIGSIO.cpp:395:12: error: ‘class igtlioConnector’ has no member named ‘SetProtocolTCP’
         c->SetProtocolTCP();
            ^~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisHardwareIGSIO/ibishardwareIGSIO.cpp:397:12: error: ‘class igtlioConnector’ has no member named ‘SetProtocolUDP’
         c->SetProtocolUDP();
            ^~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisHardwareIGSIO/ibishardwareIGSIO.cpp:398:12: error: ‘class igtlioConnector’ has no member named ‘SetDeviceName’; did you mean ‘GetDevice’?
         c->SetDeviceName( serverName );
            ^~~~~~~~~~~~~
            GetDevice
/home/anka/ibis_work_sysQt/ibis/IbisHardwareIGSIO/ibishardwareIGSIO.cpp:399:12: error: ‘class igtlioConnector’ has no member named ‘SetDeviceType’; did you mean ‘GetDevice’?
         c->SetDeviceType( deviceType );
            ^~~~~~~~~~~~~
            GetDevice
IbisHardwareIGSIO/CMakeFiles/IbisHardwareIGSIO.dir/build.make:101: recipe for target 'IbisHardwareIGSIO/CMakeFiles/IbisHardwareIGSIO.dir/ibishardwareIGSIO.cpp.o' failed

**Comment by errollgarner** [comment]
I'm sorry, it's a mistake. I wasn't building against the master of OpenIGTLinkIO. I'll integrate my changes into OpenIGTLinkIO's master first. It will fix the issue.

**Comment by hgueziri** [comment]
What's the status of this PR?

**Comment by errollgarner** [comment]
I haven't gotten around to doing it yet. I can close it for now and reopen it when it's ready.
